### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by morphykuffour** [nix-community/nix-init#100]
![image](https://user-images.githubusercontent.com/23323356/230731186-5eb59cf9-9669-4d4c-865c-53090c28cf1b.png)

The installation instructions do not work. nix-init is also not available on https://search.nixos.org/packages

**Comment by figsoda** [comment]
This loooks like an internet issue, could you try the same command again?

nix-init is currently only available on unstable branches, so it doesn't show up in the default search page
https://search.nixos.org/packages?channel=unstable&query=nix-init

**Comment by figsoda** [comment]
I will go ahead and close this since I haven't received a response. FYI nix-init is in nixpkgs 23.05 now, so you don't have to use an unstable branch now. Feel free to reopen this or create a new issue if you are still having issues with installing nix-init.
