### ISSUE TITLE
Abort when building subPackages

### ISSUE THREAD

**Issue by mbrasch** [nix-community/nix-init#117]
I am trying to build an older version of consul (1.6.1). nix-init runs without errors, but the generated nix-file cannot be built:

> error: builder for '/nix/store/ahdvdiwv0l1z2ik5cylf9pqvfz8smrdd-consul-1.6.1.drv' failed with exit code 1;
       last 10 log lines:
       > go: finding module for package github.com/hashicorp/consul/api/watch
       > go: finding module for package github.com/hashicorp/consul/api
       > go: finding module for package github.com/hashicorp/consul/sdk/freeport
       > go: finding module for package github.com/hashicorp/consul/sdk/testutil
       > go: finding module for package github.com/hashicorp/consul/sdk/testutil/retry
       > sentinel/scope.go:4:2: cannot query module due to -mod=vendor
       > agent/agent.go:38:2: cannot query module due to -mod=vendor
       > agent/testagent.go:26:2: cannot query module due to -mod=vendor
       > agent/testagent.go:27:2: cannot query module due to -mod=vendor
       > agent/testagent.go:28:2: cannot query module due to -mod=vendor

What can I do here? (I have no experience with go.)

**Comment by figsoda** [comment]
consul 1.6.1 doesn't seem to support go modules and wouldn't work with `buildGoModule`.
consule is packaged in nixpkgs, and here is the package when it was 1.6.1 (using `buildGoPackage` instead), hopefully this helps
https://github.com/NixOS/nixpkgs/blob/9641405a4a5cbbfe9aed3b013a29e1cd4206f6b1/pkgs/servers/consul/default.nix

**Comment by mbrasch** [comment]
Thank you. Do I have to create an inputs.nixpkgsXYZ = github:nixos/nixpkgs/<commit> for inputs.nixpkgs? And what would that mean for the evaluation(time/place) with 3 more different commits?

**Comment by figsoda** [comment]
You should be able to just copy-paste that if you don't want to get another version of nixpkgs
