### ISSUE TITLE
Document how to use the -n attribute

### ISSUE THREAD

**Issue by happysalada** [nix-community/nix-init#191]
Hey, first of all thanks a lot for this, this is absolutely amazing.

I am having trouble figuring out how to populate the `-n` attribute.
I use flakes, so I don't have anything in my nix-channels.
When I first started using the fetchPypi I got
```
Error: command exited with exit status: 1
stdout:

stderr:
error: attribute 'fetchPypi' missing

       at «string»:1:48:

            1| let pname="pyre-extensions";version="0.0.30";in(import(<nixpkgs>){}).fetchPypi {
             |                                                ^
            2|     inherit pname version;
```
so I was thinking that my nixpkgs is somehow old on my system.
I use flakes and nixpkgs-unstable, so I'm not sure where the nixpkgs is actually fetched from.
Then I tried to supply different values to that `-n` argument, and couldn't find anything that worked. I tried
`.`
`<nixpkgs-unstable>` (this probably doesn't work because I don't have channels
`https://github.com/nixos/nixpkgs`

not sure how to make this work properly.

Thanks again for the amazing software, this is a game changer!

**Comment by figsoda** [comment]
The issue does seem to be outdated nixpkgs, due to the recently dropped support for 22.11 (c8d505c3143a3a46fe5f96e88786393d9ea92ef7)

 You can use `./.` to use the current directory, or `builtins.getFlake "nixpkgs"` to use the flake registry

I added some more information in 3b87ac24a63e1b18e72d9730b9906827d0417feb

**Comment by happysalada** [comment]
Amazing!
Thanks again for this great package, this is such a game changer.
