### ISSUE TITLE
Python: detect format by inspecting source

### ISSUE THREAD

**Issue by FRidh** [nix-community/nix-init#20]
The format can be determined by checking the source/sdist. In case there is a `pyproject.toml` with a `build-system` section, then the format should be `pyproject`. It is also possible then to extract the `nativeBuildInputs` from it. If it is not, but there is a `setup.py`, it should be `setuptools`. When neither, it is probably best to keep it open.

**Comment by figsoda** [comment]
nix-init already recognizes both `pyproject.toml` and `setup.py` and allows you to choose between the two when both are present (defaulting to pyproject). Without either files, nix-init doesn't even know this is a python package.

**Comment by FRidh** [comment]
Ahh, I misunderstood the UI then. I thought it made me choose.
