### ISSUE TITLE
edge case in pyproject parser

### ISSUE THREAD

**Issue by blaggacao** [nix-community/nix-init#22]
https://github.com/nix-community/nix-init/blob/4c94dd20f91ea24cc176670b7b2eea6236f97c0d/src/python.rs#L70-L83

```toml
dependencies = [
    "Click>=7.0",
    "GitPython~=3.1.30",
    "honcho",
    "Jinja2~=3.0.3",
    "python-crontab~=2.6.0",
    "requests",
    "semantic-version~=2.8.2",
    "setuptools>40.9.0",
    "tomli;python_version<'3.11'",
]
```

`tomli;python_version` is parsed as `tomlipython-version` but is appears to be the https://pypi.org/project/tomli/ package. Not sure what the `;` notation conveys.

**Comment by blaggacao** [comment]
I'll add it here, althoug it's strictly a different feature, but close:

https://github.com/frappe/bench/blob/b9e9eac4115b74e3f6adccc2739ae2f7f8f9db1f/pyproject.toml#L45-L48

`hatchling` wasn't detected as the build system

**Comment by figsoda** [comment]
> hatchling wasn't detected as the build system

this is worth a new issue
