### ISSUE TITLE
Failing to resolve a certain PyPI package 

### ISSUE THREAD

**Issue by FRidh** [nix-community/nix-init#32]
Got a case where `nix-init` does not get meta data:

    $ nix-init -u https://pypi.org/project/starlette-testclient/ packages/starlette-testclient/default.nix

**Comment by figsoda** [comment]
Fetching metadata should be fixed in https://github.com/nix-community/nix-init/commit/f4f61e9ffcedc744d3d09e057571b86db8cce7bf, but I ran into another issue with this specific package. I will take a look

**Comment by FRidh** [comment]
I think there is also an issue when the package artifact uses an underscore instead of a dash.

**Comment by FRidh** [comment]
Some background on that. In the past, PyPI served directly from these urls. Then, they created a new site (warehouse) and all artifacts now have some hash. Because people liked the old urls (including us), they put a translator in the front.
