### ISSUE TITLE
pypi: make extras optional

### ISSUE THREAD

**Issue by FRidh** [nix-community/nix-init#34]
All extras seem to be added by default. I don't think this is a good default. Just now my package had extra's with really old packages, from 2007, for a completely uninteresting feature.

**Comment by FRidh** [comment]
Note I personally consider this a bug, because it nows requiring checking the sdists for what dependencies they specify and remove those that are not needed.

As an additional improvement for handling dependencies, consider the approach in Nixpkgs where we add these extras to `passthru.optional-dependencies`.

**Comment by figsoda** [comment]
fixed in https://github.com/nix-community/nix-init/commit/be61bad413c7c7d25baec4ecde6c75ac9993abac
